services:
  app:
    build: .  
    container_name: sap-migration
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always 

  redis:
    image: "redis:7-alpine"
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379" 
